<?php

namespace ContainerXzHlPEM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CY634EWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cY634EW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cY634EW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'hygieneRepository' => ['privates', 'App\\Repository\\HygieneRepository', 'getHygieneRepositoryService', true],
        ], [
            'hygieneRepository' => 'App\\Repository\\HygieneRepository',
        ]);
    }
}
