<?php

namespace ContainerXzHlPEM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHygieneService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.1lN00u6.App\Entity\Hygiene' shared service.
     *
     * @return \App\Entity\Hygiene
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.1lN00u6": it references class "App\\Entity\\Hygiene" but no such service exists.');
    }
}
