<?php

namespace ContainerZnu8iQd;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBebeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.utDPBgJ.App\Entity\Bebe' shared service.
     *
     * @return \App\Entity\Bebe
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.utDPBgJ": it references class "App\\Entity\\Bebe" but no such service exists.');
    }
}
