<?php

namespace ContainerCxByK2Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FdGtrBRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FdGtrBR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FdGtrBR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bebe' => ['privates', '.errored..service_locator.FdGtrBR.App\\Entity\\Bebe', NULL, 'Cannot autowire service ".service_locator.FdGtrBR": it references class "App\\Entity\\Bebe" but no such service exists.'],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'bebe' => 'App\\Entity\\Bebe',
            'slugger' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
