<?php

namespace ContainerCxByK2Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRepasService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.DxReJxZ.App\Entity\Repas' shared service.
     *
     * @return \App\Entity\Repas
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.DxReJxZ": it references class "App\\Entity\\Repas" but no such service exists.');
    }
}
