<?php

namespace ContainerSZB4jjW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2b0bJXRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2b0bJXR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2b0bJXR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'callApiService' => ['privates', 'App\\Service\\CallApiService', 'getCallApiServiceService', true],
            'conseilRepo' => ['privates', 'App\\Repository\\ConseilRepository', 'getConseilRepositoryService', true],
            'evenementRepository' => ['privates', 'App\\Repository\\EvenementRepository', 'getEvenementRepositoryService', true],
        ], [
            'callApiService' => 'App\\Service\\CallApiService',
            'conseilRepo' => 'App\\Repository\\ConseilRepository',
            'evenementRepository' => 'App\\Repository\\EvenementRepository',
        ]);
    }
}
