<?php

namespace ContainerSZB4jjW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LEE18h1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LEE18h1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LEE18h1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'conseilRepo' => ['privates', 'App\\Repository\\ConseilRepository', 'getConseilRepositoryService', true],
        ], [
            'conseilRepo' => 'App\\Repository\\ConseilRepository',
        ]);
    }
}
