<?php

namespace ContainerGOf1xbH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UtDPBgJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.utDPBgJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.utDPBgJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bebe' => ['privates', '.errored..service_locator.utDPBgJ.App\\Entity\\Bebe', NULL, 'Cannot autowire service ".service_locator.utDPBgJ": it references class "App\\Entity\\Bebe" but no such service exists.'],
        ], [
            'bebe' => 'App\\Entity\\Bebe',
        ]);
    }
}
