<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRxl0Cke\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRxl0Cke/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerRxl0Cke.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerRxl0Cke\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerRxl0Cke\App_KernelProdContainer([
    'container.build_hash' => 'Rxl0Cke',
    'container.build_id' => '9e27519f',
    'container.build_time' => 1627290328,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRxl0Cke');
