<?php

namespace ContainerN2ex7b4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ByMuCeFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.byMuCeF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.byMuCeF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bebeRepo' => ['privates', 'App\\Repository\\BebeRepository', 'getBebeRepositoryService', true],
            'utilisateurRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'bebeRepo' => 'App\\Repository\\BebeRepository',
            'utilisateurRepo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
