<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Bebe extends \App\Entity\Bebe implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Bebe' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Bebe' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Bebe' . "\0" . 'date_naissance', '' . "\0" . 'App\\Entity\\Bebe' . "\0" . 'poids', '' . "\0" . 'App\\Entity\\Bebe' . "\0" . 'taille', '' . "\0" . 'App\\Entity\\Bebe' . "\0" . 'genre', '' . "\0" . 'App\\Entity\\Bebe' . "\0" . 'users', '' . "\0" . 'App\\Entity\\Bebe' . "\0" . 'evenements'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Bebe' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Bebe' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Bebe' . "\0" . 'date_naissance', '' . "\0" . 'App\\Entity\\Bebe' . "\0" . 'poids', '' . "\0" . 'App\\Entity\\Bebe' . "\0" . 'taille', '' . "\0" . 'App\\Entity\\Bebe' . "\0" . 'genre', '' . "\0" . 'App\\Entity\\Bebe' . "\0" . 'users', '' . "\0" . 'App\\Entity\\Bebe' . "\0" . 'evenements'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Bebe $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom(string $prenom): \App\Entity\Bebe
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNaissance(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNaissance', []);

        return parent::getDateNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNaissance(\DateTimeInterface $date_naissance): \App\Entity\Bebe
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNaissance', [$date_naissance]);

        return parent::setDateNaissance($date_naissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getPoids(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoids', []);

        return parent::getPoids();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoids(int $poids): \App\Entity\Bebe
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoids', [$poids]);

        return parent::setPoids($poids);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaille(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaille', []);

        return parent::getTaille();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaille(int $taille): \App\Entity\Bebe
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaille', [$taille]);

        return parent::setTaille($taille);
    }

    /**
     * {@inheritDoc}
     */
    public function getGenre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGenre', []);

        return parent::getGenre();
    }

    /**
     * {@inheritDoc}
     */
    public function setGenre(string $genre): \App\Entity\Bebe
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGenre', [$genre]);

        return parent::setGenre($genre);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsers(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsers', []);

        return parent::getUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function addUsers(\App\Entity\User $users): \App\Entity\Bebe
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsers', [$users]);

        return parent::addUsers($users);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUsers(\App\Entity\User $users): \App\Entity\Bebe
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUsers', [$users]);

        return parent::removeUsers($users);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvenements(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvenements', []);

        return parent::getEvenements();
    }

    /**
     * {@inheritDoc}
     */
    public function addEvenement(\App\Entity\Evenement $evenement): \App\Entity\Bebe
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEvenement', [$evenement]);

        return parent::addEvenement($evenement);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEvenement(\App\Entity\Evenement $evenement): \App\Entity\Bebe
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEvenement', [$evenement]);

        return parent::removeEvenement($evenement);
    }

}
