<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Hygiene extends \App\Entity\Hygiene implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Hygiene' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Hygiene' . "\0" . 'couche_urine', '' . "\0" . 'App\\Entity\\Hygiene' . "\0" . 'couche_selle', '' . "\0" . 'App\\Entity\\Hygiene' . "\0" . 'bain', '' . "\0" . 'App\\Entity\\Hygiene' . "\0" . 'evenements'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Hygiene' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Hygiene' . "\0" . 'couche_urine', '' . "\0" . 'App\\Entity\\Hygiene' . "\0" . 'couche_selle', '' . "\0" . 'App\\Entity\\Hygiene' . "\0" . 'bain', '' . "\0" . 'App\\Entity\\Hygiene' . "\0" . 'evenements'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Hygiene $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCoucheUrine(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoucheUrine', []);

        return parent::getCoucheUrine();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoucheUrine(bool $couche_urine): \App\Entity\Hygiene
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoucheUrine', [$couche_urine]);

        return parent::setCoucheUrine($couche_urine);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoucheSelle(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoucheSelle', []);

        return parent::getCoucheSelle();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoucheSelle(bool $couche_selle): \App\Entity\Hygiene
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoucheSelle', [$couche_selle]);

        return parent::setCoucheSelle($couche_selle);
    }

    /**
     * {@inheritDoc}
     */
    public function getBain(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBain', []);

        return parent::getBain();
    }

    /**
     * {@inheritDoc}
     */
    public function setBain(bool $bain): \App\Entity\Hygiene
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBain', [$bain]);

        return parent::setBain($bain);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvenements(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvenements', []);

        return parent::getEvenements();
    }

    /**
     * {@inheritDoc}
     */
    public function addEvenement(\App\Entity\Evenement $evenement): \App\Entity\Hygiene
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEvenement', [$evenement]);

        return parent::addEvenement($evenement);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEvenement(\App\Entity\Evenement $evenement): \App\Entity\Hygiene
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEvenement', [$evenement]);

        return parent::removeEvenement($evenement);
    }

}
