<?php

namespace Container341SdZj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSoinListeControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\SoinListeController' shared autowired service.
     *
     * @return \App\Controller\SoinListeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/SoinListeController.php';

        $container->services['App\\Controller\\SoinListeController'] = $instance = new \App\Controller\SoinListeController();

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\SoinListeController', $container));

        return $instance;
    }
}
