<?php

namespace ContainerCxUDNCf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RmBGUdHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rmBGUdH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rmBGUdH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\EvenementController::delete' => ['privates', '.service_locator.m32XZm7', 'get_ServiceLocator_M32XZm7Service', true],
            'App\\Controller\\EvenementController::edit' => ['privates', '.service_locator.m32XZm7', 'get_ServiceLocator_M32XZm7Service', true],
            'App\\Controller\\EvenementController::index' => ['privates', '.service_locator.7sw9MSK', 'get_ServiceLocator_7sw9MSKService', true],
            'App\\Controller\\EvenementController::show' => ['privates', '.service_locator.m32XZm7', 'get_ServiceLocator_M32XZm7Service', true],
            'App\\Controller\\RepasController::delete' => ['privates', '.service_locator.DxReJxZ', 'get_ServiceLocator_DxReJxZService', true],
            'App\\Controller\\RepasController::edit' => ['privates', '.service_locator.DxReJxZ', 'get_ServiceLocator_DxReJxZService', true],
            'App\\Controller\\RepasController::index' => ['privates', '.service_locator.3aTd9kz', 'get_ServiceLocator_3aTd9kzService', true],
            'App\\Controller\\RepasController::show' => ['privates', '.service_locator.DxReJxZ', 'get_ServiceLocator_DxReJxZService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\EvenementController:delete' => ['privates', '.service_locator.m32XZm7', 'get_ServiceLocator_M32XZm7Service', true],
            'App\\Controller\\EvenementController:edit' => ['privates', '.service_locator.m32XZm7', 'get_ServiceLocator_M32XZm7Service', true],
            'App\\Controller\\EvenementController:index' => ['privates', '.service_locator.7sw9MSK', 'get_ServiceLocator_7sw9MSKService', true],
            'App\\Controller\\EvenementController:show' => ['privates', '.service_locator.m32XZm7', 'get_ServiceLocator_M32XZm7Service', true],
            'App\\Controller\\RepasController:delete' => ['privates', '.service_locator.DxReJxZ', 'get_ServiceLocator_DxReJxZService', true],
            'App\\Controller\\RepasController:edit' => ['privates', '.service_locator.DxReJxZ', 'get_ServiceLocator_DxReJxZService', true],
            'App\\Controller\\RepasController:index' => ['privates', '.service_locator.3aTd9kz', 'get_ServiceLocator_3aTd9kzService', true],
            'App\\Controller\\RepasController:show' => ['privates', '.service_locator.DxReJxZ', 'get_ServiceLocator_DxReJxZService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\EvenementController::delete' => '?',
            'App\\Controller\\EvenementController::edit' => '?',
            'App\\Controller\\EvenementController::index' => '?',
            'App\\Controller\\EvenementController::show' => '?',
            'App\\Controller\\RepasController::delete' => '?',
            'App\\Controller\\RepasController::edit' => '?',
            'App\\Controller\\RepasController::index' => '?',
            'App\\Controller\\RepasController::show' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\EvenementController:delete' => '?',
            'App\\Controller\\EvenementController:edit' => '?',
            'App\\Controller\\EvenementController:index' => '?',
            'App\\Controller\\EvenementController:show' => '?',
            'App\\Controller\\RepasController:delete' => '?',
            'App\\Controller\\RepasController:edit' => '?',
            'App\\Controller\\RepasController:index' => '?',
            'App\\Controller\\RepasController:show' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
