<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZnu8iQd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZnu8iQd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZnu8iQd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZnu8iQd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZnu8iQd\App_KernelDevDebugContainer([
    'container.build_hash' => 'Znu8iQd',
    'container.build_id' => '162ab14f',
    'container.build_time' => 1626951723,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZnu8iQd');
