<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPhdZN8i\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPhdZN8i/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPhdZN8i.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPhdZN8i\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPhdZN8i\App_KernelDevDebugContainer([
    'container.build_hash' => 'PhdZN8i',
    'container.build_id' => '73820615',
    'container.build_time' => 1627231638,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPhdZN8i');
