<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVC2T2ev\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVC2T2ev/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVC2T2ev.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVC2T2ev\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVC2T2ev\App_KernelDevDebugContainer([
    'container.build_hash' => 'VC2T2ev',
    'container.build_id' => '7197bbc2',
    'container.build_time' => 1626944673,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVC2T2ev');
