<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evenement extends \App\Entity\Evenement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'bebe', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'repas', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'hygiene', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'dodo', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'heure_debut', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'heure_fin'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'bebe', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'repas', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'hygiene', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'dodo', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'heure_debut', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'heure_fin'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Evenement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Entity\User $user): \App\Entity\Evenement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getBebe(): ?\App\Entity\Bebe
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBebe', []);

        return parent::getBebe();
    }

    /**
     * {@inheritDoc}
     */
    public function setBebe(?\App\Entity\Bebe $bebe): \App\Entity\Evenement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBebe', [$bebe]);

        return parent::setBebe($bebe);
    }

    /**
     * {@inheritDoc}
     */
    public function getRepas(): ?\App\Entity\Repas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepas', []);

        return parent::getRepas();
    }

    /**
     * {@inheritDoc}
     */
    public function setRepas(?\App\Entity\Repas $repas): \App\Entity\Evenement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRepas', [$repas]);

        return parent::setRepas($repas);
    }

    /**
     * {@inheritDoc}
     */
    public function getHygiene(): ?\App\Entity\Hygiene
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHygiene', []);

        return parent::getHygiene();
    }

    /**
     * {@inheritDoc}
     */
    public function setHygiene(?\App\Entity\Hygiene $hygiene): \App\Entity\Evenement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHygiene', [$hygiene]);

        return parent::setHygiene($hygiene);
    }

    /**
     * {@inheritDoc}
     */
    public function getDodo(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDodo', []);

        return parent::getDodo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDodo(bool $dodo): \App\Entity\Evenement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDodo', [$dodo]);

        return parent::setDodo($dodo);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeureDebut(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeureDebut', []);

        return parent::getHeureDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeureDebut(\DateTimeInterface $heure_debut): \App\Entity\Evenement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeureDebut', [$heure_debut]);

        return parent::setHeureDebut($heure_debut);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeureFin(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeureFin', []);

        return parent::getHeureFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeureFin(?\DateTimeInterface $heure_fin): \App\Entity\Evenement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeureFin', [$heure_fin]);

        return parent::setHeureFin($heure_fin);
    }

}
